src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Billing_DateTime__c</fullName>
        <label>Billing DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Billing_Status__c</fullName>
        <label>Billing Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Line_Item_Name__c</fullName>
        <label>Invoice Line Item Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Line_Item_Status__c</fullName>
        <label>Invoice Line Item Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Price__c</fullName>
        <formula>Invoice_Quantity__c *  Item_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>INVL-{000000000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/InvoiceLineItemController.cls
public with sharing class InvoiceLineItemController {
    @AuraEnabled(cacheable=true)
    public static List<Invoice_Line_Item__c> getInvoiceLineItems(Id invoiceId, String status){
        String query ='SELECT Id, Invoice_Line_Item_Name__c,Invoice_Line_Item_Status__c,Total_Price__c FROM Invoice_Line_Item__c WHERE Invoice__c =:invoiceId';
        if(String.isNotBlank(status))
            query+= ' AND Invoice_Line_Item_Status__c=:status';
        return Database.query(query);
    }
    //To fetch Invoice Line Items for passed Invoices
    @AuraEnabled(cacheable=true)
    public static List<Invoice_Line_Item__c> getINVL(Id invoiceId){
        String query ='SELECT Id, Invoice_Line_Item_Name__c,Invoice_Line_Item_Status__c,Total_Price__c FROM Invoice_Line_Item__c WHERE Invoice__c =:invoiceId';
        return Database.query(query);
    }
    //To delete Invoice Line Items based on provided Id
    @AuraEnabled
    public static void deleteINVL(Id invlId){
        try{
            delete new Invoice_Line_Item__c(Id = invlId);
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    //To fetch Invoice Line Items for passed Invoices
    @AuraEnabled
    public static List<Invoice__c> getAllInvoice(){
        return [SELECT Id,Name, Billing_DateTime__c,Billing_Status__c,Price__c FROM Invoice__c];
    }

}